# Generated by Django 4.1.7 on 2023-09-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(choices=[('Strength', 'Strength'), ('Cardio', 'Cardio')], max_length=255),
        ),
    ]
