# Generated by Django 4.1.7 on 2023-09-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_program_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='program',
            field=models.CharField(choices=[('Strength', 'Strength'), ('Cardio', 'Cardio')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
