# Generated by Django 4.1.7 on 2023-09-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_schedule_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='days',
        ),
        migrations.AddField(
            model_name='schedule',
            name='days',
            field=models.ManyToManyField(to='schedule.day'),
        ),
    ]
